INSERT INTO `config` VALUES (1, 'protocol', 'http://');
INSERT INTO `config` VALUES (2, 'version', '0.0.1');
INSERT INTO `config` VALUES (3, 'max_free_servers', '1');
INSERT INTO `config` VALUES (4, 'free_order', 'TRUE');
INSERT INTO `config` VALUES (5, 'default_language', 'cz');
INSERT INTO `config` VALUES (6, 'default_style', 'Turbo');
INSERT INTO `config` VALUES (7, 'time_zone', 'Europe/Bratislava');
INSERT INTO `config` VALUES (8, 'template_keywords', 'Hosting, Host, Server Hosting, Server Host, Game S');
INSERT INTO `config` VALUES (9, 'template_description', 'Game Server Hosting');
INSERT INTO `config` VALUES (10, 'cost_samp', '1.667');
INSERT INTO `config` VALUES (11, 'banner_rate', '100');
INSERT INTO `config` VALUES (12, 'url_userfriendly', '1');
INSERT INTO `config` VALUES (13, 'password_hash', '45E85G1H8UJ');
